/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import MAIN.Create_Account;
import MAIN.MAIN_GUI;
import GUI.Custom.TableValue;
import java.awt.Insets;
import javax.swing.UIManager;

/**
 *
 * @author Hiệp Nguyễn
 */
public class Confirm_Management extends javax.swing.JPanel {

    public static int tab;

    public Confirm_Management() {
        initComponents();
        UIManager.getDefaults().put("TabbedPane.contentBorderInsets", new Insets(0, 0, 0, 0));
        UIManager.getDefaults().put("TabbedPane.tabAreaInsets", new Insets(0, 0, 0, 0));
        UIManager.getDefaults().put("TabbedPane.tabsOverlapBorder", true);
        tbp_Confirm.addTab("Đơn đăng ký thành viên", MAIN_GUI.ca);
//        MAIN_GUI.ca.setBounds(0, 0, 990, 600);
        tbp_Confirm.addTab("Đơn mượn thiết bị ", MAIN_GUI.cbdv);
//        MAIN_GUI.cbdv.setBounds(0, 0, 990, 600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbp_Confirm = new javax.swing.JTabbedPane();

        setPreferredSize(new java.awt.Dimension(1030, 700));

        tbp_Confirm.setPreferredSize(new java.awt.Dimension(1030, 700));
        tbp_Confirm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbp_ConfirmStateChanged(evt);
            }
        });
        tbp_Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbp_ConfirmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbp_Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tbp_Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbp_ConfirmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbp_ConfirmStateChanged

    }//GEN-LAST:event_tbp_ConfirmStateChanged

    private void tbp_ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbp_ConfirmMouseClicked
        if (tbp_Confirm.getSelectedIndex() == 0) {
            tab = 0;
        } else {
            tab = 1;
        }
        if (Confirm_Management.tab == 0) {

        } else {

        }
    }//GEN-LAST:event_tbp_ConfirmMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane tbp_Confirm;
    // End of variables declaration//GEN-END:variables
}
